
FROM node:18-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:18-alpine


WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/package.json /app/package.json
COPY --from=build /app/node_modules ./node_modules

ENV NODE_ENV=production

EXPOSE 3005

CMD ["node", "dist/main"]
